config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :secret_codes, only: [:index, :create]
  root to: 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    end
  end
end

app/models/secret_code.rb
class SecretCode < ActiveRecord::Base
  belongs_to :user
  validates :code, uniqueness: true, presence: true

  def self.generate(count = 1)
    return [] if count < 1
    (1..count).map do
      code = new(code: generate_unique_code)
      code.save(validate: false)
      code
    end
  end

  def self.generate_unique_code
    begin
      code = SecureRandom.hex(5)
    end while exists?(code: code)
    code
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable, :rememberable
  attr_accessor :code

  has_one :secret_code, dependent: :nullify
  validate :check_if_code_exist?, on: :create

  after_create :assign_secret_code, unless: :admin?

  def admin?
    self.role.to_s == 'admin'
  end

  private

  def check_if_code_exist?
    return if code.blank?
    if not SecretCode.exists?(user_id: nil, code: code)
      errors.add(:secret_code, I18n.t('errors.messages.invalid'))
    end
  end

  def assign_secret_code
    secret_code = SecretCode.find_by(code: code)
    secret_code.update_column(:user_id, id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:code])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
  load_and_authorize_resource

  def index
    @secret_codes = SecretCode.all
  end

  def create
    count = Integer(params[:count]) rescue 1
    @secret_codes = SecretCode.generate(count)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def menu_item(name=nil, path="#", *args, &block)
    path = name || path if block_given?
    return if path.eql?(request.original_fullpath)

    options = args.extract_options!
    content_tag :li, :class => is_active?(path, options) do
      if block_given?
        link_to path, options, &block
      else
        link_to name, path, options, &block
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UsersSecret</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/secret_codes/_generate.html.erb
<p>
  <b>Generate Unique Codes</b>
</p>

<%= form_tag secret_codes_path, remote: true do %>
  <%= select_tag(:count, options_for_select([10, 1, 2, 20, 50, 100])) %>
  <%= submit_tag 'Generate' %>
<% end %>

app/views/secret_codes/_row.html.erb
<tr>
  <td><%= secret.code %></td>
  <td><%= secret.user.try(:email) %></td>
</tr>

app/views/secret_codes/create.js.erb
<% if @secret_codes.present? %>
  $('.secret_codes tr.header').after("<%= escape_javascript(render partial: 'row', collection: @secret_codes, as: :secret) %>")
<% end %>

app/views/secret_codes/index.html.erb
<table class="table secret_codes">
  <tr class="header">
    <th>Code</th>
    <th>Email</th>
  </tr>
  <%= render partial: 'row', collection: @secret_codes, as: :secret %>
</table>

<%= render 'generate' %>

app/views/shared/_header.html.erb
<%= nav_bar fixed: :top do %>
  <%= menu_group pull: :right do %>
    <% if current_user %>
      <li><%= menu_item :Home, root_path %></li>
      <li><%= menu_item :Codes, secret_codes_path if can? :read, SecretCode %></li>
      <li><%= menu_item :Logout, destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= menu_item :Login, new_user_session_path %></li>
      <li><%= menu_item :Register, new_user_registration_path %></li>
    <% end %>
  <% end %>
<% end %>